### ISSUE TITLE
OpenVRML 0.18.9 does not compile with Boost 1.65.1

### ISSUE THREAD

**Issue by raphael-st** [bradenmcd/openvrml#3]
This [patch](https://trac.macports.org/attachment/ticket/55301/patch-vrml97_grammar.h.diff) solves some of the problems, but now I get
```
In file included from libopenvrml/openvrml/local/uri.cpp:21:
In file included from libopenvrml/openvrml/local/uri.h:26:
In file included from /opt/local/include/boost/spirit/include/phoenix1.hpp:11:
In file included from /opt/local/include/boost/spirit/home/classic/phoenix.hpp:18:
/opt/local/include/boost/spirit/home/classic/phoenix/special_ops.hpp:62:48: error: no member named 'complex' in namespace 'std'
template <typename T> struct rank<PHOENIX_STD::complex<T> >
                                  ~~~~~~~~~~~~~^
/opt/local/include/boost/spirit/home/classic/phoenix/special_ops.hpp:62:56: error: 'T' does not refer to a value
template <typename T> struct rank<PHOENIX_STD::complex<T> >
                                                       ^
/opt/local/include/boost/spirit/home/classic/phoenix/special_ops.hpp:62:20: note: declared here
template <typename T> struct rank<PHOENIX_STD::complex<T> >
                   ^
```
See the [corresponding MacPorts  ticket](https://trac.macports.org/ticket/55301).

**Comment by cooljeanius** [comment]
Is this project still even alive? The most recent commit is from almost 5 years ago now...

**Comment by bradenmcd** [comment]
> Is this project still even alive? The most recent commit is from almost 5 years ago now...

Not really. Anyone interested in carrying it forward should fork it.

**Comment by cooljeanius** [comment]
> > Is this project still even alive? The most recent commit is from almost 5 years ago now...
> 
> Not really. Anyone interested in carrying it forward should fork it.

...so maybe mark the repo as "archived" then?
